-- MySQL Script generated by MySQL Workbench
-- 08/23/14 21:22:16
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `idFaculties` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFaculties`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `idDepartments` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `idProfessors` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `idStudents` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `idFaculty` INT NOT NULL,
  `Faculties_idFaculties` INT NOT NULL,
  PRIMARY KEY (`idStudents`, `Faculties_idFaculties`),
  INDEX `fk_Students_Faculties_idx` (`Faculties_idFaculties` ASC),
  CONSTRAINT `fk_Students_Faculties`
    FOREIGN KEY (`Faculties_idFaculties`)
    REFERENCES `mydb`.`Faculties` (`idFaculties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `idTitles` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTitles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `idCourses` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCourses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProfessorsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProfessorsCourses` (
  `idProfessors` INT NOT NULL,
  `idCourses` INT NOT NULL,
  `Professors_idProfessors` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  PRIMARY KEY (`idProfessors`, `idCourses`, `Professors_idProfessors`, `Courses_idCourses`),
  INDEX `fk_ProfessorsCourses_Professors1_idx` (`Professors_idProfessors` ASC),
  INDEX `fk_ProfessorsCourses_Courses1_idx` (`Courses_idCourses` ASC),
  CONSTRAINT `fk_ProfessorsCourses_Professors1`
    FOREIGN KEY (`Professors_idProfessors`)
    REFERENCES `mydb`.`Professors` (`idProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorsCourses_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProfessorsTitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProfessorsTitles` (
  `idProfessors` INT NOT NULL,
  `idTitles` INT NOT NULL,
  `Professors_idProfessors` INT NOT NULL,
  `Titles_idTitles` INT NOT NULL,
  PRIMARY KEY (`idProfessors`, `idTitles`, `Professors_idProfessors`, `Titles_idTitles`),
  INDEX `fk_ProfessorsTitles_Professors1_idx` (`Professors_idProfessors` ASC),
  INDEX `fk_ProfessorsTitles_Titles1_idx` (`Titles_idTitles` ASC),
  CONSTRAINT `fk_ProfessorsTitles_Professors1`
    FOREIGN KEY (`Professors_idProfessors`)
    REFERENCES `mydb`.`Professors` (`idProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProfessorsTitles_Titles1`
    FOREIGN KEY (`Titles_idTitles`)
    REFERENCES `mydb`.`Titles` (`idTitles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DepartmentsProfessors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DepartmentsProfessors` (
  `idDepartments` INT NOT NULL,
  `idProfessors` INT NOT NULL,
  `Professors_idProfessors` INT NOT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idDepartments`, `idProfessors`, `Professors_idProfessors`, `Departments_idDepartments`),
  INDEX `fk_DepartmentsProfessors_Professors1_idx` (`Professors_idProfessors` ASC),
  INDEX `fk_DepartmentsProfessors_Departments1_idx` (`Departments_idDepartments` ASC),
  CONSTRAINT `fk_DepartmentsProfessors_Professors1`
    FOREIGN KEY (`Professors_idProfessors`)
    REFERENCES `mydb`.`Professors` (`idProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DepartmentsProfessors_Departments1`
    FOREIGN KEY (`Departments_idDepartments`)
    REFERENCES `mydb`.`Departments` (`idDepartments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DepartmentsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DepartmentsCourses` (
  `idDepartments` INT NOT NULL,
  `idCourses` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idDepartments`, `idCourses`, `Courses_idCourses`, `Departments_idDepartments`),
  INDEX `fk_DepartmentsCourses_Courses1_idx` (`Courses_idCourses` ASC),
  INDEX `fk_DepartmentsCourses_Departments1_idx` (`Departments_idDepartments` ASC),
  CONSTRAINT `fk_DepartmentsCourses_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DepartmentsCourses_Departments1`
    FOREIGN KEY (`Departments_idDepartments`)
    REFERENCES `mydb`.`Departments` (`idDepartments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StudentsCourses` (
  `idStudents` INT NOT NULL,
  `idCourses` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudents` INT NOT NULL,
  `Students_Faculties_idFaculties` INT NOT NULL,
  PRIMARY KEY (`idStudents`, `idCourses`, `Courses_idCourses`, `Students_idStudents`, `Students_Faculties_idFaculties`),
  INDEX `fk_StudentsCourses_Courses1_idx` (`Courses_idCourses` ASC),
  INDEX `fk_StudentsCourses_Students1_idx` (`Students_idStudents` ASC, `Students_Faculties_idFaculties` ASC),
  CONSTRAINT `fk_StudentsCourses_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentsCourses_Students1`
    FOREIGN KEY (`Students_idStudents` , `Students_Faculties_idFaculties`)
    REFERENCES `mydb`.`Students` (`idStudents` , `Faculties_idFaculties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FacultiesDepartments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FacultiesDepartments` (
  `idFaculties` INT NOT NULL,
  `idDepartments` INT NOT NULL,
  `Faculties_idFaculties` INT NOT NULL,
  `Departments_idDepartments` INT NOT NULL,
  PRIMARY KEY (`idFaculties`, `idDepartments`, `Faculties_idFaculties`, `Departments_idDepartments`),
  INDEX `fk_FacultiesDepartments_Faculties1_idx` (`Faculties_idFaculties` ASC),
  INDEX `fk_FacultiesDepartments_Departments1_idx` (`Departments_idDepartments` ASC),
  CONSTRAINT `fk_FacultiesDepartments_Faculties1`
    FOREIGN KEY (`Faculties_idFaculties`)
    REFERENCES `mydb`.`Faculties` (`idFaculties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacultiesDepartments_Departments1`
    FOREIGN KEY (`Departments_idDepartments`)
    REFERENCES `mydb`.`Departments` (`idDepartments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
